### ISSUE TITLE
Optimize design for low-power

### ISSUE THREAD

**Issue by SloMusti** [IRNAS/nodemcu-devkit-v1.0#2]
See 
 * https://github.com/nodemcu/nodemcu-devkit-v1.0/issues/26 and other 
 * https://tinker.yeoman.com.au/2016/05/29/running-nodemcu-on-a-battery-esp8266-low-power-consumption-revisited/
 * https://www.losant.com/blog/making-the-esp8266-low-powered-with-deep-sleep

**Comment by VojislavM** [comment]
This is done in the new version of Irnas-NodeMCU board: https://github.com/IRNAS/nodemcu-devkit-v1.0/releases/tag/v0.1
