### ISSUE TITLE
Make CP2102 USB powered

### ISSUE THREAD

**Issue by SloMusti** [IRNAS/nodemcu-devkit-v1.0#3]
Change the configuration such that CP2102 is USB powered, not from the 3v3 regulator, following changes are required:

* Disconnect pins 6 and 7 from 3v3 line
* Connect pin 7 only to 5V USB in line

**Comment by VojislavM** [comment]
This is done in the new version of Irnas-NodeMCU board: https://github.com/IRNAS/nodemcu-devkit-v1.0/releases/tag/v0.1
