### ISSUE TITLE
Power consumption mesurment

### ISSUE THREAD

**Issue by VojislavM** [IRNAS/nodemcu-devkit-v1.0#4]
Measure power consumption of Irnas-NodeMCU:
* normal mode
* deep sleep
* Modem-sleep
* Light-sleep

![esp8266_sleep_options](https://user-images.githubusercontent.com/8199477/27032865-17a397da-4f77-11e7-87f8-962266d77981.png)

**Comment by SloMusti** [comment]
No need to measure this, only standby power consumption of voltage regulator.
